esphome:
  name: sensor
  friendly_name: Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: "Axwo0w29jYAPECo8yvyRjkY/JUABdoryzUc6cAfytm0="

ota:
  platform: esphome
  password: "9fb5068eb03ebb9dc85e0db25bba9013"

web_server:
  port: 80

wifi:
  ssid: "ORBI97"
  password: "elatednest901"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 10.0.0.64
    # Set this to the IP address of the router. Often ends with .1
    gateway: 10.0.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gas-Sensor Fallback Hotspot"
    password: "X3kiFEgPIdPz"

sensor:
  - platform: adc
    pin: GPIO35
    name: Smoke
    device_class: gas    
    update_interval: 60s                
    filters:
      - multiply: 100
    unit_of_measurement: "%"
 
  - platform: adc
    pin: GPIO33
    name: CO
    device_class: carbon_monoxide
    update_interval: 60s     
    filters:
       - multiply: 100
    unit_of_measurement: "%"





switch:
  - platform: gpio
    pin: GPIO32
    name: Buzzer
    restore_mode: ALWAYS_ON
    